[tool.poetry]
name = "bob"
description = "Sends voice messages"
version = "1.0.0"
authors = ["BlindfoldedSurgery <team@blindfolded.surgery>"]
license = "MIT"

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.blindfolded.surgery"
priority = "explicit"

[tool.poetry.dependencies]
aiofiles = "^23.0.0"
azure-cognitiveservices-speech = "^1.28.0"
bs-config = { version = "1.0.1", extras = ["dotenv"], source = "internal" }
certifi = "2024.2.2"
click = "^8.1.3"
Deprecated = "^1.2.13"
google-cloud-firestore = "^2.7.3"
google-cloud-texttospeech = "^2.13.0"
google-cloud-translate = "^3.9.0"
google-cloud-vision = "^3.2.0"
injector = "^0.21.0"
langcodes = "^3.3.0"
language-data = "1.1"
more-itertools = "^10.0.0"
pendulum = "^3.0.0"
python = "~3.11"
python-telegram-bot-raw = "20.8"
sentry-sdk = "^1.14.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
mypy = "~1.8"
pytest = "^8.0.0"
ruff = "0.2.2"
types-aiofiles = "^22.1.0"
types-cachetools = "^5.2.1"
types-Deprecated = "^1.2.9"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "asyncache"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "azure.*"
ignore_missing_imports = true

[tool.ruff]
extend-select = [
    "I001",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.isort]
known-first-party = ["bob"]
