---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  serviceName: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: secrets
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          volumeMounts:
            - mountPath: /secrets/sa.json
              name: secrets
              subPath: GSA_JSON
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/sa.json
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
