---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bob
  serviceName: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      serviceAccountName: bob
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: gsa-json
          secret:
            secretName: gsa-json
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          volumeMounts:
            - mountPath: /secrets
              name: gsa-json
              readOnly: true
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gsa.json
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bob
spec:
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: bob
    kind: StatefulSet
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-headless.nats-system.svc.cluster.local:8222"
        account: "$G"
        stream: "telegram-updates"
        consumer: "speech-bot"
