---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bob
  serviceName: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      serviceAccountName: bob
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets
          secret:
            secretName: secrets
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          volumeMounts:
            - mountPath: /secrets
              name: gsa-json
              readOnly: true
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gsa.json
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 200m
