---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gsa-json
spec:
  secretStoreRef:
    name: scaleway-prep-speech-bot
    kind: ClusterSecretStore
  data:
    - secretKey: gsa.json
      remoteRef:
        key: "name:gsa-json"
        decodingStrategy: None
