---
apiVersion: v1
kind: Service
metadata:
  name: bob
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  serviceName: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
        - name: app
          image: {{ .Values.image.app }}
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
