apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  SERVICE_ACCOUNT_JSON: {{ .Values.google.serviceAccountJsonB64 }}
  TELEGRAM_TOKEN: {{ .Values.telegram.apiKey | quote }}
stringData:
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
