apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  SERVICE_ACCOUNT_JSON: "{{ .Values.google.serviceAccountJsonB64 }}"
stringData:
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  AZURE_SPEECH_KEY: "{{ .Values.azure.speechKey }}"
  TELEGRAM_TOKEN: "{{ .Values.telegram.apiKey }}"
