name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v1
    with:
      python-version: '3.11'
      debian-version: bullseye

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v1
    with:
      python-version: '3.11'
      debian-version: bullseye

  build-container-image:
    needs:
      - lint
      - test
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: warp-ubuntu-latest-arm64-2x
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: born-prep
    container: ghcr.io/bjoernpetersen/helm:2.1.1
    needs:
      - build-container-image
    if: success() && github.ref_name == github.event.repository.default_branch
    concurrency: production
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - uses: actions/checkout@v4
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm upgrade bob . --install --namespace=bob --atomic
          kubeconfig: '${{ secrets.BORN_KUBECONFIG_RAW }}'

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v3
